---
title: "SenseBox statistics"
author: "Johannes Friedrich"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
  fig_caption: yes
fig_height: 7
fig_width: 7
number_sections: yes
toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center")
library(sp)
library(rworldmap)
library(senseBox)
library(tidyverse)
library(lubridate)

theme_update(axis.text = element_text(size = 14),
             axis.title = element_text(size = 14, face = "bold"),
             legend.text = element_text(size = 12),
             legend.title = element_text(size = 12, face = "bold"))
```

## Load senseBox Ids

```{r}
data <- search_senseBox()
```

## Calculate analytics

```{r}
data %>% 
  select(createdAt,
         exposure) %>% 
  mutate(
    year = year(createdAt)
  ) %>% 
  group_by(exposure, year) %>% 
  summarise(
    n = n()
  ) %>% 
  ggplot() +
  geom_bar(aes(x=year, y = n, fill = exposure), stat = "identity") +
  ggtitle("Number of senseboxes")
```

```{r}
data %>% 
  select(phenomena) %>% 
  unlist()  %>% 
  unname %>% 
  #unique() %>% 
  as_data_frame() %>%  
  group_by(value) %>% 
    summarise(n = n()) %>% 
  # ungroup() %>% 
  top_n(5, n)
```

